### ISSUE TITLE
Request for citation info

### ISSUE THREAD

**Issue by spcanelon** [rdboyes/forester#13]
Hi @rdboyes! I'm the person who [originally asked for help](https://twitter.com/spcanelon/status/1320832482334396416?s=20) in doing what `forester` does and you have absolutely delivered! Thanks so much! 😃 
I've enjoyed playing around with the package to create figures for a research publication and I'd like to be able to properly cite `forester` in the manuscript (in the next ~6 weeks). Could you let me know how you'd like me to populate a citation entry?

Here's an example of the info that could be included:

```
> citation("gtsummary")

To cite package ‘gtsummary’ in publications use:

  Daniel D. Sjoberg, Margie Hannum, Karissa Whiting and Emily C. Zabor (2020). gtsummary:
  Presentation-Ready Data Summary and Analytic Result Tables. R package version 1.3.2.
  https://CRAN.R-project.org/package=gtsummary

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {gtsummary: Presentation-Ready Data Summary and Analytic Result Tables},
    author = {Daniel D. Sjoberg and Margie Hannum and Karissa Whiting and Emily C. Zabor},
    year = {2020},
    note = {R package version 1.3.2},
    url = {https://CRAN.R-project.org/package=gtsummary},
  }
```

Alternatively, I know `forester` is not on CRAN (yet!) but [this CRAN resource on Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html#CITATION-files) could be helpful if you want to create a CITATION file.

**Comment by rdboyes** [comment]
I'm glad it's been helpful! I've attempted to add citation information in the package, and included a text version of the citation (patterned after other R package citation styles - hopefully correct?) as follows: 

Boyes, Randy (2021). Forester: An R package for creating publication-ready forest plots. R package version 0.3.0. Available at: https://github.com/rdboyes/forester

Thanks for bringing this up (and for giving me the idea for the package in the first place!)

**Comment by spcanelon** [comment]
Excellent, thanks so much!

**Comment by spcanelon** [comment]
Looks great! 👏 

```
> citation("forester")

To cite forester in publications use:

  Boyes, Randy (2021). Forester: An R package for creating publication-ready forest plots. R
  package version 0.3.0. Available at: https://github.com/rdboyes/forester

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {Forester: An R package for creating publication-ready forest plots.},
    author = {Randy Boyes},
    year = {2021},
    note = {R package version 0.3.0},
    url = {https://github.com/rdboyes/forester},
  }
```
