### ISSUE TITLE
Support for optional scientific notation printing

### ISSUE THREAD

**Issue by spcanelon** [rdboyes/forester#17]
Hi @rdboyes, I'm realizing I have some values in my dataset that are too large to be printed "as is" in the forester plot right-side table. Could you point me to where I could make an adjustment so that these values get printed in scientific notation?

I'm taking a guess it would involve modifing the following code? https://github.com/rdboyes/forester/blob/a83634e1d71cca7ea133e9d051594b2ee8b6c1cf/R/forester.R#L75-L80

**Comment by rdboyes** [comment]
There's an optional argument to the function called `right_side_data` that you can pass a data frame to and override the default display of the right side. If you pass a data frame with one column of character formatted scientific notation numbers, it should work! Let me know if it doesn't -

**Comment by spcanelon** [comment]
Ah! I'll try that, thank you!

**Comment by spcanelon** [comment]
Sadly, I tried using `right_side_data` with the example dataset and it didn't work for me. To test it, I defined the right hand side to be the `Subgroup` column of the example dataset (i.e. a copy of that column), removed the estimate and confidence interval arguments, and received this error:

```
Error in data.frame(estimate = estimate, ci_low = ci_low, ci_high = ci_high) : 
  argument "estimate" is missing, with no default
```

**Comment by spcanelon** [comment]
I got it working Randy, thanks so much!
