### ISSUE TITLE
Code in README doesn't work from user aspect

### ISSUE THREAD

**Issue by ShixiangWang** [rdboyes/forester#26]
Hi,

I found this package is pretty cool, however, I cannot run the data loading commands.

Please replace `here::here("inst/extdata/example_figure_data.xlsx")` with `system.file("extdata", "example_figure_data.xlsx", package = "forester")`

Best,

Shixiang

**Comment by ShixiangWang** [comment]
I also have some questions, when the `display=TRUE`, is it possible to directly output a ggplot object? I checked the output and found the figure is a bit large.

![image](https://user-images.githubusercontent.com/25057508/113498130-bf993f80-953c-11eb-99e3-bd75023eb61d.png)

 Is it why you output the image and read the file to display? If so, please increase the default dpi, it is very hard to read at the default.

![image](https://user-images.githubusercontent.com/25057508/113498171-1ef74f80-953d-11eb-9ee9-0e9880ca2b08.png)

Besides, the `file_path` option should not set to user current directory at default, use setting like `file.path(tempdir(), "forester_plot.png")` is a better option.

**Comment by rdboyes** [comment]
Thanks! You're right about these points - I will change them in a future update

**Comment by higgi13425** [comment]
Hi Randy - can you add an example or two of data files that are formatted appropriately for use by forester? I think a description of how to format will be really helpful.

It think it would also be helpful to create a helper function (forestize??) to convert a tidy data file (with columns like Sex, Age, BMI, race, baseline statin, metabolic disease, renal function) from the original tidy file to a data frame formatted for forester use. Likely some combination of groupie/count/pivot longer for this....

**Comment by rdboyes** [comment]
These issues have been fixed in the most recent release - thanks for the suggestions

**Comment by higgi13425** [comment]
Neat! Will check it out!
    On Saturday, October 30, 2021, 05:39:08 PM EDT, Randall Boyes ***@***.***> wrote:  
 
 


Closed #26.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
