### ISSUE TITLE
Option to export to vector file format

### ISSUE THREAD

**Issue by spcanelon** [rdboyes/forester#29]
Hi @rdboyes!

I have a manuscript with some {forester} figures currently under review and was notified that all figures need to be in vector file format so that the in-house designers can make aesthetic modifications.

Would it be possble for you to add the ability to export the figures to a vector file format (e.g. PDF, EPS) rather than a raster image format like PNG?

Thanks for considering, and by the way at least one reviewer thought the figures looked "very attractive" 👏🏽

**Comment by rdboyes** [comment]
This is an option I've been meaning to add, but early tests showed it unleashed absolute havoc on the alignment of elements. Let me push an update that allows it ... but you'll have to play with the alignment settings to get it looking reasonable

**Comment by spcanelon** [comment]
I'll give it a go, thanks @rdboyes!

**Comment by rdboyes** [comment]
This works for real with the most recent release using `render_as = "pdf"`
