### ISSUE TITLE
Header line is cut off when plotting few lines

### ISSUE THREAD

**Issue by drveera** [rdboyes/forester#32]
Hi, 

This is a beautiful package.  I am so excited to use this. But often I'd like to plot only few lines of data. When I do that, I see the header line is getting truncated. Do you have a fix for that?

Thanks
-Veera

**Comment by rdboyes** [comment]
Thanks - the newest version now includes a `nudge_height` option to adjust the height of the output plot area.

**Comment by drveera** [comment]
Thank you very much

**Comment by miyyyang** [comment]
Hi, I am facing the same problem and I found that increasing nudge_height will stretch the plot and it doesn't match the table, is there any solution for this?
