### ISSUE TITLE
Pooled AUC Forest Plot

### ISSUE THREAD

**Issue by codeenthusiast** [rdboyes/forester#41]
I am doing a meta-analysis for a diagnostic test where the studies report AUC's with respective confidence intervals. I also have the sample size pertaining to each study. Is it possible to do a pooled AUC forest plot and if yes, would you have any recommendations on how to get started? Thank you.

**Comment by rdboyes** [comment]
Hi - this package has a very narrow scope. The only thing it is intended to do is add a plot in the middle of a table of numbers that you have already calculated. So ... if you can calculate the correct estimates and CIs elsewhere, then yes, this package will allow you to plot them
