### ISSUE TITLE
Forest plot x-axis name

### ISSUE THREAD

**Issue by rxy6** [rdboyes/forester#42]
Add the ability to either title the actual forest plot part of the plot or add an x-axis label.

**Comment by rdboyes** [comment]
Can you be more specific about what you want? The forest plot is just a visual describing the Estimate column, and you can change the name of that column. The "arrows" allow a form of x axis label. Alternatively, if you want to customize further that that, you can use `center_ggplot` to completely override the middle plot

**Comment by rxy6** [comment]
We're creating a forest plot with both unadjusted and adjusted estimates included in the table and we want to be clear which estimates are actually plotted, so something like "Adj OR (95% CI)" above the plot, or just "Adjusted OR" as the x-axis label. The text for the arrows at the bottom does not give enough space to adequately describe what either direction means in our case. Thanks!
