### ISSUE TITLE
Precision of x-axis labels

### ISSUE THREAD

**Issue by ryan-andrews** [rdboyes/forester#44]
Hello,

I have estimates and 95% CI that range from approximately -0.1 to 0.1. When I use the forester() function, I use the default xlim and xbreaks arguments, and the resulting forest plot seemingly has two 0.0 labels. From the forest plot, the left-most 0.0 should be -0.05, but it seems like the x-axis labels are truncated to only be multiples of 0.1?

To test this, I reran the call to forester(), specifying xlim=c(-0.15, 0.15) and breaks = c(-0.15, -0.1, -0.05, 0, 0.05, 0.1, 0.15), and the x-axis labels displayed were -0.1, -0.1, 0.0, 0.0, 0.0, 0.1, 0.1. The second digit after the decimal is indeed being lost/not displayed.

Is there a way to change the precision of the x-axis labels that are displayed?

![main_cog_result_forest-2023-01-26](https://user-images.githubusercontent.com/7597974/214926166-338135b4-8ff3-439a-9ac2-ffc857effe25.png)

**Comment by rdboyes** [comment]
Hi - this isn't currently an available option, but there is the option to overwrite the whole middle ggplot if you'd like something different displayed with the option `center_ggplot` - sorry, I can't add options for every possible tweak!
