### ISSUE TITLE
Why is it misplaced?

### ISSUE THREAD

**Issue by pomang-211** [rdboyes/forester#45]
<img width="170" alt="屏幕截图 2023-02-28 110545" src="https://user-images.githubusercontent.com/76840516/221743235-91e380b5-ee13-4e5e-84c2-042d1fef7379.png">

**Comment by rdboyes** [comment]
Hello - there are many things that influence alignment, and if you just provide half a screenshot it's impossible for me to know what caused it. Try the nudge_y parameter, it is meant to fix alignment issues like this
