### ISSUE TITLE
Get ggplot object

### ISSUE THREAD

**Issue by jinseob2kim** [rdboyes/forester#47]
Thanks for great package!!

Could I get the ggplot object? As I know, This package only supports img file.

I want to save the plot with PPT (using officer/rvg package)

Sincerely
Jinseob Kim

**Comment by rdboyes** [comment]
Hi - you can use the option `render_as = "rmarkdown"` to get the patchwork object directly. Alternatively, you can specify a number of output options directly instead of the default `"png"`, including `"svg"` if that is your target format

**Comment by jinseob2kim** [comment]
Thanks! I get pptx with `render_as = "rmarkdown"`
