### ISSUE TITLE
Transform x axis

### ISSUE THREAD

**Issue by Fleurmlmstr** [rdboyes/forester#48]
Hi! 
Great package, very neat. 
I was wondering if there is a way to transform the x axis and plot to e.g. a log scale?

Thanks!

**Comment by rdboyes** [comment]
Hi - yes, there is an option `x_scale_linear` that defaults to `TRUE`, change it to `FALSE` for a log scale. If you want more control, you can replace the whole central ggplot with whatever you want (use the option `center_ggplot = your_plot`)
