### ISSUE TITLE
add_plot argument missing from docs

### ISSUE THREAD

**Issue by paulsharpeY** [rdboyes/forester#5]
`forester_0.2.0`

I see it [in the source](R/forester.R), but not in the docs when I install:

![forester](https://user-images.githubusercontent.com/61544260/104294089-ae4d1380-54b6-11eb-8860-b5de54714251.jpg)

**Comment by rdboyes** [comment]
Thanks! I had just forgotten to run `document()` after adding it. Should be fixed now.
